name: Format

on: [push, pull_request]

jobs:
  linux-format:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo ./scripts/install-deps-linux.sh

      - name: Format
        run: ./scripts/format.sh --dry-run
