name: Format

on: [push, pull_request]

jobs:
  linux-format:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          cd client
          SUDO=""
          if command -v sudo &>/dev/null; then
              SUDO="sudo"
          fi
          $SUDO ./scripts/install-deps-linux.sh

      - name: Format
        run: |
          cd client
          ./scripts/format.sh --dry-run
